name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build -x test -i --no-daemon -Dspring.profiles.active=prod

      # Docker Image Build and Push
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

        # CD 배포
      - name: Deploy remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.APPCENTER_SERVER_IP}}
          username: ${{secrets.APPCENTER_SERVER_USERNAME}}
          password: ${{secrets.APPCENTER_SERVER_PASSWORD}}
          port: ${{secrets.APPCENTER_SERVER_PORT}}
          script: |
            cd /home/serverking/ingle
            
            docker network create ingle-network || true
            
            # 기존 컨테이너 중지 및 삭제
            if [ "$(docker ps -aq -f name=${{secrets.DOCKER_REPO}})" ]; then
              docker stop ${{secrets.DOCKER_REPO}}
              docker rm ${{secrets.DOCKER_REPO}}
            fi
            
            # 기존 Redis 컨테이너 중지 및 삭제
            if [ "$(docker ps -aq -f name=ingle-redis)" ]; then
              docker stop ingle-redis
              docker rm ingle-redis
            fi
            
            # Redis 컨테이너 새로 실행 (포트 6385 바인딩)
            docker run -d --name ingle-redis --network ingle-network -p 6385:6379 --restart unless-stopped redis:latest
            
             # 새 컨테이너 실행
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            docker run -d \
              --name ${{ secrets.DOCKER_REPO }} \
              --network ingle-network \
              --env SPRING_PROFILES_ACTIVE=prod \
              --env JAVA_TOOL_OPTIONS="-Duser.timezone=Asia/Seoul" \
              --env MYSQL_URL=${{ secrets.DB_URL }} \
              --env MYSQL_USERNAME=${{ secrets.DB_USERNAME }} \
              --env MYSQL_PASSWORD=${{ secrets.DB_PASSWORD }} \
              --env ORACLE_URL=${{ secrets.ORACLE_URL }} \
              --env ORACLE_USERNAME=${{ secrets.ORACLE_USERNAME }} \
              --env ORACLE_PASSWORD=${{ secrets.ORACLE_PASSWORD }} \
              --env JWT_SECRET=${{ secrets.JWT_SECRET }} \
              --env SERVER_URL=${{ secrets.SERVER_URL }} \
              --env-file /home/serverking/ingle/.env \
              -p 8089:8089 \
                ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}